CREATE OR REPLACE SHARE LOAN_PAYMENTS_SHARE;

GRANT USAGE ON DATABASE LOAN_PAYMENTS TO SHARE LOAN_PAYMENTS_SHARE;

GRANT USAGE ON SCHEMA LOAN_PAYMENTS.BRONZE TO SHARE LOAN_PAYMENTS_SHARE;

GRANT SELECT ON TABLE LOAN_PAYMENTS.BRONZE.EMPLOYEES TO SHARE LOAN_PAYMENTS_SHARE;

SHOW GRANTS TO SHARE LOAN_PAYMENTS_SHARE;

ALTER SHARE LOAN_PAYMENTS_SHARE ADD ACCOUNT=GP21624;