CREATE OR REPLACE TABLE LOAN_PAYMENTS.BRONZE.ORDERS (
ORDER_ID VARCHAR(50),
AMOUNT INT,
PROFIT INT,
QUANTITY INT,
CATEGORY VARCHAR(30),
SUBCATEGORY VARCHAR(30)
);

SELECT * FROM LOAN_PAYMENTS.BRONZE.ORDERS;

COPY INTO LOAN_PAYMENTS.BRONZE.ORDERS
FROM @LOAN_PAYMENTS.EXTERNAL_STAGES.aws_stage
file_format=(type = csv, FIELD_DELIMITER=',', skip_header=1)
files = ('OrderDetails.csv');

CREATE OR REPLACE TABLE LOAN_PAYMENTS.BRONZE.ORDERS_EX (
ORDER_ID VARCHAR(50),
AMOUNT INT,
PROFIT INT,
PROFIT_FLAG VARCHAR(30)
);

COPY INTO LOAN_PAYMENTS.BRONZE.ORDERS_EX
FROM (SELECT 
    s.$1,
    s.$2,
    s.$3,
    CASE WHEN CAST(s.$3 as int) < 0 THEN 'not profitable' ELSE 'Profitable' END
FROM 
    @LOAN_PAYMENTS.EXTERNAL_STAGES.aws_stage as s)
file_format=(type = csv, FIELD_DELIMITER=',', skip_header=1)
files = ('OrderDetails.csv');

SELECT * FROM LOAN_PAYMENTS.BRONZE.ORDERS_EX;