CREATE OR REPLACE DATABASE LOAN_PAYMENTS;

CREATE OR REPLACE SCHEMA EXTERNAL_STAGES;

CREATE OR REPLACE STAGE LOAN_PAYMENTS.EXTERNAL_STAGES.aws_stage
    url = 's3://bucketsnowflakes3';

LIST @LOAN_PAYMENTS.EXTERNAL_STAGES.aws_stage;    

CREATE OR REPLACE SCHEMA LOAN_PAYMENTS.BRONZE;

CREATE OR REPLACE STAGE LOAN_PAYMENTS.EXTERNAL_STAGES.aws_stage_error
    url = 's3://bucketsnowflakes4';

LIST @LOAN_PAYMENTS.EXTERNAL_STAGES.aws_stage_error;    