SELECT * FROM LOAN_PAYMENTS.BRONZE.EMPLOYEES;

UPDATE LOAN_PAYMENTS.BRONZE.EMPLOYEES SET salary = 45000 WHERE id = 1;

SELECT * FROM LOAN_PAYMENTS.BRONZE.EMPLOYEES WHERE id=1;

SELECT * FROM LOAN_PAYMENTS.BRONZE.EMPLOYEES AT (OFFSET => -10*60);

DROP TABLE LOAN_PAYMENTS.BRONZE.EMPLOYEES;

SELECT * FROM LOAN_PAYMENTS.BRONZE.EMPLOYEES;

UNDROP TABLE LOAN_PAYMENTS.BRONZE.EMPLOYEES;

DESC TABLE LOAN_PAYMENTS.BRONZE.EMPLOYEES;

SHOW TABLES LIKE '%EMPLOYEES%';