SELECT * FROM LOAN_PAYMENTS.BRONZE.EMPLOYEES;

CREATE TABLE LOAN_PAYMENTS.BRONZE.EMPLOYEES_CLONE
CLONE LOAN_PAYMENTS.BRONZE.EMPLOYEES;

SELECT * FROM LOAN_PAYMENTS.BRONZE.EMPLOYEES_CLONE;
UPDATE LOAN_PAYMENTS.BRONZE.EMPLOYEES_CLONE SET salary = 52000 WHERE id = 1;